// apps/carmen/src/components/Toast/index.tsx
import { CheckCircleIcon } from 'lucide-react'

import { useToast } from 'src/lib/toast/hooks'
import type { ToastMessage } from 'src/lib/toast/types'

const Toast = () => {
  const { messages } = useToast()

  const ToastItem = ({ message }: { message: ToastMessage }) => {
    return (
      <div className={`alert alert-${message.type}`}>
        {message.type === 'success' && <CheckCircleIcon size={16} className="w-4 h-4 mr-2" />}
        <span>{message.text}</span>
      </div>
    )
  }

  return (
    <div className="toast toast-center z-50 bottom-20">
      {messages.map((message) => (
        <ToastItem key={message.text} message={message} />
      ))}
    </div>
  )
}

export default Toast

// apps/carmen/src/components/Toast/index.svelte
<script lang="ts">
  import { CheckCircleIcon } from 'lucide-svelte'
  import { toastStore } from 'src/lib/toast/store'
  import type { ToastMessage } from 'src/lib/toast/types'
  
  // Subscribe to the toast store
  $: messages = $toastStore.messages
</script>

<div class="toast toast-center z-50 bottom-20">
  {#each messages as message (message.text)}
    <div class="alert alert-{message.type}">
      {#if message.type === 'success'}
        <CheckCircleIcon size={16} class="w-4 h-4 mr-2" />
      {/if}
      <span>{message.text}</span>
    </div>
  {/each}
</div>
