// apps/carmen/src/components/AppLink/index.svelte
<script lang="ts">
  import { Link, useLocation } from 'svelte-navigator'
  import { twMerge } from 'tailwind-merge'
  
  export let to: string
  export let btn: boolean = false
  export let className: string = ''
  
  // Get current location to check if link is active
  const location = useLocation()
  $: isActive = $location.pathname === to
</script>

{#if btn}
  <Link {to} {...$$restProps}>
    <span class={twMerge('btn btn-primary text-white px-4 py-3 hover:cursor-pointer', className)}>
      <slot></slot>
    </span>
  </Link>
{:else}
  <Link 
    {to} 
    class={twMerge('text-black', isActive ? 'bg-blue-100' : null, className)} 
    {...$$restProps}
  >
    <slot></slot>
  </Link>
{/if}

// apps/carmen/src/components/AppLink/index.tsx
import type { PropsWithChildren } from 'react'
import { Link, useMatches } from 'react-router-dom'
import { twMerge } from 'tailwind-merge'

const AppLink = ({
  btn,
  to,
  className,
  children,
  ...props
}: PropsWithChildren<
  React.HTMLProps<HTMLAnchorElement> & {
    btn?: boolean
    className?: string
    to: string
  }
>) => {
  if (btn) {
    return (
      <Link to={to} {...props}>
        <span
          className={twMerge(
            'btn btn-primary text-white px-4 py-3 hover:cursor-pointer',
            className
          )}
        >
          {children}
        </span>
      </Link>
    )
  }

  return (
    <Link
      to={to}
      className={twMerge(
        'text-black',
        useMatches().some((match) => match.pathname === to) ? 'bg-blue-100' : null,
        className
      )}
      {...props}
    >
      {children}
    </Link>
  )
}

export default AppLink
