// apps/rocco/app/components/lists/lists.tsx
import { Plus } from 'lucide-react'
import { Link, useRouteLoaderData } from 'react-router'
import { trpc } from '~/lib/trpc/client'
import Loading from '../loading'

export default function Lists() {
  const layoutData = useRouteLoaderData('routes/layout') as { isAuthenticated: boolean } | undefined
  const isAuthenticated = layoutData?.isAuthenticated ?? false

  const {
    data: lists = [],
    isLoading,
    error,
  } = trpc.lists.getAll.useQuery(undefined, { enabled: isAuthenticated })

  return (
    <div className="space-y-4 w-full">
      <div className="flex items-center justify-between">
        <h2 className="text-2xl italic font-light text-gray-900">Lists</h2>
        <Link
          to="/lists/create"
          className="self-start flex items-center gap-2 px-3 py-2 bg-indigo-600 hover:bg-indigo-700 active:bg-indigo-700 text-white text-sm font-medium rounded-md transition-colors"
        >
          <Plus size={16} className="inline" />
        </Link>
      </div>

      {isLoading ? (
        <div className="flex items-center justify-center h-32">
          <Loading size="lg" />
        </div>
      ) : error ? (
        <div className="text-center py-8">
          <p className="text-red-600">Error loading lists: {error.message}</p>
        </div>
      ) : lists.length === 0 ? (
        <div className="flex flex-col items-center justify-center rounded-xl border border-dashed border-gray-300 bg-white p-10 text-center">
          <h3 className="text-lg font-semibold text-gray-900">No lists yet</h3>
          <p className="mt-1 text-sm text-gray-600">Get started by creating your first list.</p>
        </div>
      ) : (
        <ul className="list-none divide-y divide-gray-200 bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
          {lists.map((list) => (
            <li key={list.id}>
              <Link
                to={`/lists/${list.id}`}
                viewTransition
                className="block px-4 py-3 hover:bg-gray-50 transition-colors"
              >
                <div className="flex items-center justify-between">
                  <h3 className="text-gray-900 truncate">{list.name}</h3>
                  <span className="bg-black text-white text-sm rounded-full px-2.5 py-1">
                    {list.places.length || 0}
                  </span>
                </div>
              </Link>
            </li>
          ))}
        </ul>
      )}
    </div>
  )
}

// apps/carmen/src/routes/Lists.svelte
<script>
import { onMount } from 'svelte'
import { navigate } from 'svelte-navigator'
import { lists, isAuthenticated } from '../lib/store'
import { LOGIN, LIST } from '../lib/routes'

// Protect route
onMount(() => {
  if (!$isAuthenticated) {
    navigate(LOGIN)
  }
})

// Mock data - would come from API
onMount(() => {
  if ($lists.length === 0) {
    lists.set([
      { id: '1', name: 'Places to Visit', description: 'My travel bucket list', itemsCount: 12 },
      { id: '2', name: 'Restaurants', description: 'Good places to eat', itemsCount: 8 },
      { id: '3', name: 'Shopping', description: 'Stores to check out', itemsCount: 5 },
    ])
  }
})

function goToList(id) {
  navigate(`/lists/${id}`)
}
</script>

<div class="min-h-screen bg-gray-50">
  <header class="bg-white shadow">
    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold text-gray-900">My Lists</h1>
    </div>
  </header>
  
  <main>
    <div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
      <div class="px-4 py-6 sm:px-0">
        <div class="flex justify-between items-center mb-6">
          <h2 class="text-2xl font-semibold text-gray-900">All Lists</h2>
          <button class="px-4 py-2 bg-blue-600 text-white rounded-md text-sm font-medium hover:bg-blue-700">
            Create New List
          </button>
        </div>
        
        <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {#each $lists as list}
            <button 
              class="w-full text-left bg-white rounded-lg shadow-sm overflow-hidden hover:shadow-md transition cursor-pointer"
              on:click={() => goToList(list.id)}
              on:keydown={e => e.key === 'Enter' && goToList(list.id)}
            >
              <div class="p-5">
                <h3 class="text-lg font-semibold text-gray-900 mb-1">{list.name}</h3>
                <p class="text-gray-600 text-sm mb-3">{list.description}</p>
                <div class="text-gray-500 text-xs font-medium">
                  {list.itemsCount} items
                </div>
              </div>
            </button>
          {/each}
        </div>
        
        {#if $lists.length === 0}
          <div class="text-center py-12">
            <p class="text-gray-500">You don't have any lists yet. Create your first list to get started!</p>
          </div>
        {/if}
      </div>
    </div>
  </main>
</div>
