// apps/rocco/app/components/lists/list-menu.tsx
import { MoreVertical } from 'lucide-react'
import React, { type PropsWithChildren } from 'react'

import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '~/components/ui/dropdown-menu'
import type { List } from '~/lib/types'
import ListEditSheet from './list-edit-sheet'

const ListMenuContext = React.createContext<{
  isEditSheetOpen: boolean
  setIsEditSheetOpen: (value: boolean) => void
  isDeleteSheetOpen: boolean
  setIsDeleteSheetOpen: (value: boolean) => void
}>({
  isEditSheetOpen: false,
  setIsEditSheetOpen: () => {},
  isDeleteSheetOpen: false,
  setIsDeleteSheetOpen: () => {},
})

const ListMenuProvider = ({ children }: PropsWithChildren) => {
  const [isEditSheetOpen, setIsEditSheetOpen] = React.useState(false)
  const [isDeleteSheetOpen, setIsDeleteSheetOpen] = React.useState(false)

  return (
    <ListMenuContext.Provider
      value={{
        isEditSheetOpen,
        setIsEditSheetOpen,
        isDeleteSheetOpen,
        setIsDeleteSheetOpen,
      }}
    >
      {children}
    </ListMenuContext.Provider>
  )
}

export function useListMenu() {
  return React.useContext(ListMenuContext)
}

type ListMenuProps = {
  list: List
  isOwnList: boolean
}
export function ListMenu({ list, isOwnList }: ListMenuProps) {
  const { setIsEditSheetOpen } = useListMenu()

  if (!isOwnList) {
    return null
  }

  return (
    <>
      <DropdownMenu>
        <DropdownMenuTrigger data-testid="list-dropdownmenu-trigger">
          <MoreVertical />
        </DropdownMenuTrigger>
        <DropdownMenuContent>
          <DropdownMenuItem className="p-2" onClick={() => setIsEditSheetOpen(true)}>
            Edit
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
      <ListEditSheet list={list} />
    </>
  )
}

export default function ListMenuWithProvider(props: ListMenuProps) {
  return (
    <ListMenuProvider>
      <ListMenu {...props} />
    </ListMenuProvider>
  )
}

// apps/carmen/src/components/Lists/list-menu.svelte
<script lang="ts">
  import { MoreVertical } from 'lucide-svelte'
  import { writable } from 'svelte/store'
  import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
  } from 'src/components/ui/dropdown-menu.svelte'
  import type { List } from 'src/lib/types'
  import ListEditSheet from './list-edit-sheet.svelte'
  
  export let list: List & { createdBy: { email: string } }
  export let isOwnList: boolean
  
  // Create stores for state management
  const isEditSheetOpen = writable(false)
  const isDeleteSheetOpen = writable(false)
  
  // Export the stores for other components to use if needed
  export { isEditSheetOpen, isDeleteSheetOpen }
</script>

{#if isOwnList}
  <DropdownMenu>
    <DropdownMenuTrigger data-testid="list-dropdownmenu-trigger">
      <MoreVertical />
    </DropdownMenuTrigger>
    <DropdownMenuContent>
      <DropdownMenuItem class="p-2" on:click={() => $isEditSheetOpen = true}>
        Edit
      </DropdownMenuItem>
    </DropdownMenuContent>
  </DropdownMenu>
  <ListEditSheet {list} bind:isOpen={$isEditSheetOpen} />
{/if}
