// apps/rocco/app/components/places/place-types.tsx
import type { HTMLAttributes } from 'react';

import { cn } from '~/lib/utils';

const EXCLUDED_TYPES = ['establishment', 'food', 'point_of_interest', 'political'];

interface PlaceTypeProps extends HTMLAttributes<HTMLSpanElement> {}

const PlaceType = ({ children, className, ...props }: PlaceTypeProps) => {
  return (
    <span
      data-testid="place-type"
      className={cn(
        'inline-flex items-center gap-1.5',
        'px-3 py-1.5',
        'text-xs font-semibold tracking-wide',
        'bg-muted',
        'border border-border',
        'text-foreground',
        className,
      )}
      {...props}
    >
      <span className="capitalize">{children}</span>
    </span>
  );
};

const PlaceTypes = ({ limit, types }: { limit?: number; types: string[] }) => {
  const filterExcludedTypes = (type: string) => !EXCLUDED_TYPES.includes(type);

  const isPointOfInterest =
    types.length === 2 && types.includes('establishment') && types.includes('point_of_interest');

  return (
    <div className="flex flex-wrap items-center gap-2.5">
      {isPointOfInterest ? (
        <PlaceType>Point of Interest</PlaceType>
      ) : (
        types
          .slice(0, limit)
          .filter(filterExcludedTypes)
          .filter((type, index, arr) => {
            void index;
            if (type === 'store' && arr.length > 1) {
              return false;
            }

            if (type.includes('_restaurant') && arr.includes('restaurant')) {
              return false;
            }

            return true;
          })
          .map((type) => (
            <PlaceType key={type}>{type.replace(/_store/gi, '').replace(/_/gi, ' ')}</PlaceType>
          ))
      )}
    </div>
  );
};

export default PlaceTypes;

// apps/carmen/src/components/places/PlaceTypes.svelte
<script lang="ts">
import PlaceType from './PlaceType.svelte'

export let limit: number | undefined = undefined
export let types: string[] = []

const excludedTypes = ['establishment', 'food', 'point_of_interest', 'political']

const filterExcludedTypes = (type: string) => !excludedTypes.includes(type)

$: isPointOfInterest =
  types.length === 2 && types.includes('establishment') && types.includes('point_of_interest')

$: displayTypes = isPointOfInterest
  ? []
  : types
      .slice(0, limit)
      .filter(filterExcludedTypes)
      .filter((type, index, arr) => {
        if (type === 'store' && arr.length > 1) {
          return false
        }
        return true
      })
</script>

<p class="flex justify-start flex-wrap gap-2">
  {#if isPointOfInterest}
    <PlaceType>Point of Interest</PlaceType>
  {:else}
    {#each displayTypes as type (type)}
      <PlaceType>{type.replace(/_/gi, " ")}</PlaceType>
    {/each}
  {/if}
</p>
