// apps/carmen/src/routes/Lists.svelte
<script>
import { onMount } from 'svelte'
import { navigate } from 'svelte-navigator'
import { lists, isAuthenticated } from '../lib/store'
import { LOGIN, LIST } from '../lib/routes'

// Protect route
onMount(() => {
  if (!$isAuthenticated) {
    navigate(LOGIN)
  }
})

// Mock data - would come from API
onMount(() => {
  if ($lists.length === 0) {
    lists.set([
      { id: '1', name: 'Places to Visit', description: 'My travel bucket list', itemsCount: 12 },
      { id: '2', name: 'Restaurants', description: 'Good places to eat', itemsCount: 8 },
      { id: '3', name: 'Shopping', description: 'Stores to check out', itemsCount: 5 },
    ])
  }
})

function goToList(id) {
  navigate(`/lists/${id}`)
}
</script>

<div class="min-h-screen bg-gray-50">
  <header class="bg-white shadow">
    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold text-gray-900">My Lists</h1>
    </div>
  </header>
  
  <main>
    <div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
      <div class="px-4 py-6 sm:px-0">
        <div class="flex justify-between items-center mb-6">
          <h2 class="text-2xl font-semibold text-gray-900">All Lists</h2>
          <button class="px-4 py-2 bg-blue-600 text-white rounded-md text-sm font-medium hover:bg-blue-700">
            Create New List
          </button>
        </div>
        
        <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {#each $lists as list}
            <button 
              class="w-full text-left bg-white rounded-lg shadow-sm overflow-hidden hover:shadow-md transition cursor-pointer"
              on:click={() => goToList(list.id)}
              on:keydown={e => e.key === 'Enter' && goToList(list.id)}
            >
              <div class="p-5">
                <h3 class="text-lg font-semibold text-gray-900 mb-1">{list.name}</h3>
                <p class="text-gray-600 text-sm mb-3">{list.description}</p>
                <div class="text-gray-500 text-xs font-medium">
                  {list.itemsCount} items
                </div>
              </div>
            </button>
          {/each}
        </div>
        
        {#if $lists.length === 0}
          <div class="text-center py-12">
            <p class="text-gray-500">You don't have any lists yet. Create your first list to get started!</p>
          </div>
        {/if}
      </div>
    </div>
  </main>
</div>

// apps/rocco/app/components/lists-components/lists.tsx
import { Plus } from 'lucide-react'
import { Link, useRouteLoaderData } from 'react-router'
import { trpc } from '~/lib/trpc/client'
import Loading from '../loading'

export default function Lists() {
  const layoutData = useRouteLoaderData('routes/layout') as { isAuthenticated: boolean } | undefined
  const isAuthenticated = layoutData?.isAuthenticated ?? false

  const {
    data: lists = [],
    isLoading,
    error,
  } = trpc.lists.getAll.useQuery(undefined, { enabled: isAuthenticated })

  return (
    <div className="space-y-4 w-full max-w-4xl mx-auto">
      <div className="flex items-center justify-between">
        <h2 className="text-2xl font-bold text-gray-900">Your Lists</h2>
        <Link
          to="/lists/create"
          className="self-start px-4 py-1.5 bg-indigo-100 hover:bg-indigo-200 text-indigo-700 text-sm font-medium rounded-lg transition-colors"
        >
          <Plus size={16} className="inline mr-1" />
          New List
        </Link>
      </div>

      {isLoading ? (
        <div className="flex items-center justify-center h-32">
          <Loading size="lg" />
        </div>
      ) : error ? (
        <div className="text-center py-8">
          <p className="text-red-600">Error loading lists: {error.message}</p>
        </div>
      ) : lists.length === 0 ? (
        <div className="flex flex-col items-center justify-center rounded-xl border border-dashed border-gray-300 bg-white p-10 text-center">
          <h3 className="text-lg font-semibold text-gray-900">No lists yet</h3>
          <p className="mt-1 text-sm text-gray-600">Get started by creating your first list.</p>
          <Link
            to="/lists/create"
            className="mt-4 inline-flex items-center px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-medium rounded-lg transition-colors"
          >
            <Plus size={16} className="mr-2" />
            Create a list
          </Link>
        </div>
      ) : (
        <div className="flex flex-col gap-4">
          {lists.map((list) => (
            <Link
              key={list.id}
              to={`/lists/${list.id}`}
              className="block px-4 py-2 bg-white rounded-xl shadow-sm hover:shadow-md transition-shadow border border-gray-200"
            >
              <div className="flex items-center justify-between">
                <h3 className="text-lg font-semibold text-gray-900 truncate">{list.name}</h3>
                <p className="text-gray-600 text-sm">
                  {list.itemCount || 0} {(list.itemCount || 0) === 1 ? 'place' : 'places'}
                </p>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-xs text-gray-500">
                  {list.isPublic ? 'Public' : 'Private'}
                </span>
              </div>
            </Link>
          ))}
        </div>
      )}
    </div>
  )
}
